### PR TITLE
Proposed sample market maker bot

### PR DESCRIPTION
**Pull request by uscott**
This is the sample market maker bot I discussed with John Jansen.

### CODE REVIEW

**Comment by kvdveer** [comment]
Hey, thanks for your contribution.

We can't really merge it in this API wrapper project. Instead, we plan on building a contrib repository, containing multiple example bots. Could you provide an introduction as to how your strategy works?

**Comment by uscott** [comment]
Sure no problem, I will get back to you soon on that. Btw the version you published apparently exposes some production API keys in it (not mine), if so you probably want to disable those immediately.

**Comment by uscott** [comment]
Hi, so the strategy summary you guys wrote for the sample market maker bot in the README.MD was close but not quite right.

The bot layers bids and offers around the market mid, which it attempts to calculate from the order book. The spread between quoted bids and offers is determined by a user-set risk charge on volatility. Volatility is estimated by an EWMA (Exponentially Weighted Moving Average Process) with frequency and parameters that may also be set by the user.

What you described, i.e. quoting around an EWMA mid price, is something that could be implemented at the user's leisure (not difficult for someone who understands the sample code), and arguably has both advantages and disadvantages.

Btw a typo of mine made it into your disclaimers. The last part should read "... with no warranty or guarantee *of* performance."

**Comment by uscott** [comment]
Also since you've published the sample code under your Github project the way you saw fit, feel free to close/deny this pull request at your leisure.

**Pull request closed without merging**
